# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release publish

on:
  release:
    types: 
      - published

jobs:
###############################################################################
# NPM Node
####
  accessibility-checker-publish:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [12.x]

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - run: npm install
        working-directory: accessibility-checker
      - run: npm run build
        working-directory: accessibility-checker
      - run: gitactions/publish/achecker.sh
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  karma-accessibility-checker-publish:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [12.x]

      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
      - run: npm install
        working-directory: karma-accessibility-checker
      - run: npm run build
        working-directory: karma-accessibility-checker
      - run: gitactions/publish/karma-achecker.sh
        env: 
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  extension-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - run: npm install
      working-directory: report-react
    - run: npm install
      working-directory: accessibility-checker-extension
    - run: |
        if [ -n "$RELEASE_VERSION" ]; then 
          sed -i 's/"version": "3.0.0"/"version": "${RELEASE_VERSION}"/g' ./manifest.json
        fi;
      working-directory: accessibility-checker-extension/src
    - run: npm run package:browser
      working-directory: accessibility-checker-extension
    - name: Upload packed extension
      uses: actions/upload-artifact@v1
      with:
        name: accessibility-checker-extension
        path: accessibility-checker-extension/package/accessibility-checker-extension.zip